### ISSUE TITLE
`region` not being passed by Cloud Scheduler

### ISSUE THREAD

**Issue by ryanaross** [GoogleCloudPlatform/active-assist#11]
The main recommendations Workflow is expecting an input of `region`:
https://github.com/GoogleCloudPlatform/active-assist/blob/883d8203f315371f2cc03c0f2ad43a4bd7b6ad26/remora-project-cleaner/terraform/modules/project-cleanup/workflows/recommendations_workflow_main.yaml#L47

But the Cloud Scheduler job is not sending this parameter:
https://github.com/GoogleCloudPlatform/active-assist/blob/883d8203f315371f2cc03c0f2ad43a4bd7b6ad26/remora-project-cleaner/terraform/modules/project-cleanup/main.tf#L211

Before adjusting this, I was getting the following error:
```
RuntimeError: "Input region not specified."
in step "checkInput", routine "main", line: 46
"Input region not specified."
```

**Comment by xiangwa** [comment]
Thank you Ryan for flagging this! We're looking into it.
